//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PracticaFEntities : DbContext
    {
        public PracticaFEntities()
            : base("name=PracticaFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contactos> Contactos { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<CursosEstudiantes> CursosEstudiantes { get; set; }
        public virtual DbSet<Estudiante> Estudiante { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
